version: '3.8'
services:

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=test
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - "db-data:/var/lib/postgresql/data"
    networks:
      - local

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/test
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - local

volumes:
  db-data: {}

networks:
  local:
    driver: bridge
